\c citas2;
CREATE TABLE IF NOT EXISTS PACDATOS (
             ID SERIAL,
             NUMERO VARCHAR (20),
             NOMBRE VARCHAR (150),
             APELLIDO1 VARCHAR (150),
             APELLIDO2 VARCHAR (150),
             NIF VARCHAR (20),
             PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CENTRO (
             ID SERIAL,
             CODIGO VARCHAR (20),
             CENTRO VARCHAR (500),
             CIF VARCHAR (20),
             PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CITASPAC (
             ID SERIAL,
             NUMEROHISTORIA VARCHAR (20),
             MEDICO VARCHAR (20),
             NOMBRE_MEDICO VARCHAR (500),
             DPTO VARCHAR (120),
             FAMTIPOCITA VARCHAR (120),
             TIPOCITA VARCHAR (120),
             FECHA VARCHAR (120),
             HORA VARCHAR (120),
             ESTADO VARCHAR (20),
             CODIGOCENTRO VARCHAR (20),
             CENTRO VARCHAR(120),
             PRIMARY KEY (ID)
);


INSERT INTO PACDATOS VALUES(DEFAULT,'01','NDEMO1','DEMO1','DEMO1','CIF1');
INSERT INTO PACDATOS VALUES(DEFAULT,'02','NDEMO2','DEMO2','DEMO2','CIF2');
INSERT INTO PACDATOS VALUES(DEFAULT,'03','NDEMO3','DEMO3','DEMO3','CIF3');
INSERT INTO PACDATOS VALUES(DEFAULT,'04','NDEMO4','DEMO4','DEMO4','CIF4');
INSERT INTO CENTRO VALUES(DEFAULT,'001','VISSUM ALICCANTE','CIFV1');
INSERT INTO CENTRO VALUES(DEFAULT,'002','VISSUM MIRASIERRA','CIFV2');
INSERT INTO CITASPAC VALUES(DEFAULT,'01','VISSUMME1','DR. VISSUMME1 DEMO1','OFT.GENERAL','REV','REVISION UNO','24/01/2020','09:00:00','FACTURADA','001','VISSUM ALICANTE');
INSERT INTO CITASPAC VALUES(DEFAULT,'01','VISSUMME1','DR. VISSUMME1 DEMO3','VISSUM CATARATAS','REV','PRIMERA VISITA','14/02/2020','19:00:00','FACTURADA','001','VISSUM ALICANTE');
INSERT INTO CITASPAC VALUES(DEFAULT,'01','VISSUMME1','DR. VISSUMME1 DEMO4','VISSUM CATARATAS','POSTOPER','POSTOPERATORIO','24/03/2020','09:00:00','FACTURADA','002','VISSUM MIRASIERRA');
INSERT INTO CITASPAC VALUES(DEFAULT,'02','VISSUMME1','DR. VISSUMME1 DEMO1','VISSUM OFT.GENERAL','POSTOPER','POSTOPERATORIO','24/01/2020','09:00:00','FACTURADA','001','VISSUM ALICANTE');
INSERT INTO CITASPAC VALUES(DEFAULT,'02','VISSUMME1','DR. VISSUMME1 DEMO1','VISSUM OFT.GENERAL','POSTOPER','CIRUGIA REFRACTICA','24/02/2020','14:00:00','FACTURADA','002','VISSUM MIRASIERRA');
INSERT INTO CITASPAC VALUES(DEFAULT,'03','VISSUMME1','DR. VISSUMME1 DEMO54','VISSUM GLAUCOMA','POSTOPER','POSTOPERATORIO','14/03/2020','15:00:00','FACTURADA','002','VISSUM MIRASIERRA');
INSERT INTO CITASPAC VALUES(DEFAULT,'04','ME1','DR.VISSUMME1 DEMO1','VISSUM OFT.GENERAL','CIRUGIA','CIRUGIA GENERAL','24/01/2020','09:00:00','FACTURADA','002','VISSUM MIRASIERRA');





